### ISSUE TITLE
High early CH4 emissions for some countries (Libya, Australia, New Zealand)

### ISSUE THREAD

**Issue by rgieseke** [JGuetschow/PRIMAP-hist#1]
As reported on Twitter (https://twitter.com/RARohde/status/1114049212403130368)

> The Libya values in the middle and the early Australia / New Zealand values feel a bit high to me.

https://www.pik-potsdam.de/paris-reality-check/primap-hist/#scenario=histcr&id=lby&entity=ch4

**Comment by JGuetschow** [comment]
Australia / New Zealand data comes from EDGAR-HYDE growthrates (livestock sector) . Libya emissions are directly from EDGAR v4.3.2 (fugitive emissions) with thew highest peak including a tiny increase from the source extrapolation algorithm.
