### ISSUE TITLE
Definition of fluorinated gases

### ISSUE THREAD

**Issue by rgieseke** [JGuetschow/PRIMAP-hist#15]
V2.0 started to include NF3: "However, NF3 has been added to the timeseries but data is only available for a few countries"

https://www.pik-potsdam.de/paris-reality-check/primap-hist/primap-hist-data-description.pdf

The original paper states: "In the remainderof the paper we use the term fluorinated gases to refer to thecombined group of gases HFCs, PFCs, and SF6."

As F-Gases still an aggregate of only the three groups/gas?

**Comment by JGuetschow** [comment]
NF3 is now included in the F-gases basket

**Comment by rgieseke** [comment]
Thanks!
