### ISSUE TITLE
Andrew 2019 reference in metadata

### ISSUE THREAD

**Issue by rgieseke** [JGuetschow/PRIMAP-hist#16]
The paper should be referenced as the 2019 version, should be possible to change by the library.

https://twitter.com/robbie_andrew/status/1203261955714236418

**Comment by JGuetschow** [comment]
I used the 2018 version, because the 2019 version was not through peer review at the time of writing the data description. I can check if it can be changed, but given the workload of the person managing the repositories, I can't promise anything. I use the correct reference in the paper.

**Comment by rgieseke** [comment]
Fair enough, it's however possible to cite such work with ESSD, so should be ok with the repo as well: 

> Works "submitted to", "in preparation", "in review", or only available as preprint should also be included in the reference list. 

https://www.earth-system-science-data.net/for_authors/manuscript_preparation.html

**Comment by JGuetschow** [comment]
Fixed for v2.2
