### ISSUE TITLE
EDGAR v5.0

### ISSUE THREAD

**Issue by JGuetschow** [JGuetschow/PRIMAP-hist#17]
Read and integrate EDGAR v5.0 data: 
https://edgar.jrc.ec.europa.eu/overview.php?v=50_GHG

Check sector mapping to IPCC 2006 for changes in EDGAR sectors. -> EDGAR v5.0 uses IPCC2006  sectors. So no sector mapping to 2006 sectors needed any more.

**Comment by rgieseke** [comment]
I have half a conversion to CSV started for https://github.com/openclimatedata/edgar-co2-emissions/

Would that be helpful to you?

**Comment by rgieseke** [comment]
In any case the repo is updated though i noted that this is CO2 only (so the report released earlier this year.)

**Comment by JGuetschow** [comment]
The full data comes in 4 xls files. They can be read using the standard routine either directly from xls or after saving to csv. So it should be quick.

**Comment by JGuetschow** [comment]
Data read

**Comment by JGuetschow** [comment]
Integrated into v2.2. which will be published soon
