### ISSUE TITLE
Timeline for PRIMAP-hist v2.3

### ISSUE THREAD

**Issue by JGuetschow** [JGuetschow/PRIMAP-hist#25]
**Timeline is work in progress**
PRIMAP-hist v2.3 will be published before COP 26 (Nov 1-12 2021). Thus the publication will be a bit earlier than usual requiring hard deadlines for data inclusion.

The data should be finalized and checked one month before the COP which is end of August. One month is needed for checking and fixes, so the first beta version will be completed beginning of August. After that no new data will be included (except if there are bugfixes in input data)

**Data sources to be updated:**

- CRF: first submissions in April / May. Later updates for some countries. cutoff date end of July #27 , #28 
- BUR: publication of individual reports throughout the year. Need a fixed cutoff date. End of June #26 
- UNFCCC: data is added to the interface irregularly. Data is easy to read, so cutoff date can be late. End of July #30
- BP: publication in June. Inclusion in alpha version #32
- Andrew Cement: Ask if update will be published
- EDGAR: find out if there will be an update #37 
- FAOstat: all sectors have updates scheduled for April 30, 2021. #31
- CDIAC: updates at  https://energy.appstate.edu/node/104 #29 
- data for 2020: to be determined (carbon monitor as a possible source)

**Comment by rgieseke** [comment]
CDIAC has continued here

https://energy.appstate.edu/node/104

Last release was 2020 with 2017 data.

https://data.ess-dive.lbl.gov/view/doi:10.15485/1712447

**Comment by JGuetschow** [comment]
Thanks, that's great!

Doesn't seem to be very well known yet. One download and 12 views.

**Comment by rgieseke** [comment]
It's also used in the GCB:

> Global and national emission estimates for coal, oil, natural gas, and peat fuel extraction from the Carbon Dioxide Information Analysis Center (CDIAC) for the time period 1750–2017 (Gilfillan et al., 2020), as it is the only data set that extends back to 1750 by country.

>Global total. The global estimate is the sum of the individual countries' emissions and international aviation and marine bunkers. The CDIAC global total differs from the sum of the countries and bunkers since (1) the sum of imports in all countries is not equal to the sum of exports because of reporting inconsistencies, (2) changes in stocks, and (3) the share of non-oxidized carbon (e.g. as solvents, lubricants, feedstocks) at the global level is assumed to be fixed at the 1970s average while it varies in the country-level data based on energy data (Andres et al., 2012). From the 2019 edition CDIAC now includes changes in stocks in the global total (Dennis Gilfillan, personal communication, 2020), removing one contribution to this discrepancy. The discrepancy has grown over time from around zero in 1990 to over 500 MtCO2 in recent years, consistent with the growth in non-oxidized carbon (IEA, 2019). To remove this discrepancy we now calculate the global total as the sum of the countries and international bunkers.

https://essd.copernicus.org/articles/12/3269/2020/

So "downloads" are mostly via GCB (who also don't cite http://doi.org/10.15485/1712447 directly).

(Also i wouldn't give too much on these counters, here some arguments why PyPI removed theirs https://stackoverflow.com/a/38102521)

**Comment by JGuetschow** [comment]
v2.3 published, so this can be closed
