### ISSUE TITLE
Monaco agriculture emissions 2013 onwards

### ISSUE THREAD

**Issue by mljeffery** [JGuetschow/PRIMAP-hist#3]
Monaco's emissions from Agriculture drop to zero suddenly in 2013 and stay at 0. I guess this is a bug rather than a feature?

<img width="1244" alt="Screen Shot 2019-04-24 at 16 02 13" src="https://user-images.githubusercontent.com/35143752/56665491-72eb2f80-66aa-11e9-8c4e-9ce66db6d1c0.png">

**Comment by JGuetschow** [comment]
Fixed since v2.1 beta2
