### ISSUE TITLE
Frequency of updates

### ISSUE THREAD

**Issue by sn2525** [JGuetschow/PRIMAP-hist#51]
Hi,

Are you able to clarify how often the data is updated and when the 2019 emission figures will be included for countries please?

Thank you in advance!

**Comment by JGuetschow** [comment]
Usually the data is updated every year. The time lag used to be 2 years (the 2021 update includes data until 2019). However, we have no long term funding so every update depends on funding from users.

The 2021 update can be found here: https://zenodo.org/record/5494497
