### ISSUE TITLE
Provenance and country colum

### ISSUE THREAD

**Issue by rgieseke** [JGuetschow/PRIMAP-hist#68]
The Readme at https://zenodo.org/record/7727475 lists a column `provenance`, which seems to be missing from the CSV.
I guess it would always be `derived` but maybe it's a missing export flag?

```
“provenance“

Provenance of the data. Here: “derived” as it is a composite source.
```

It also lists `country` which is actually `area` (I guess that's primap2 lingo).

**Comment by JGuetschow** [comment]
Thanks for spotting. I've fixed in the code and the data description. will be implemented in v2.5
