### ISSUE TITLE
Several previously reported area, entity, category combinations dropped in v2.4.2

### ISSUE THREAD

**Issue by coroa** [JGuetschow/PRIMAP-hist#72]
v2.4.2 in comparison to October's v2.4 lost a few time-series:
```
MultiIndex([('ABW', 'CH4',      '3.A'),
            ('ABW', 'CH4',     'M.AG'),
            ('ABW', 'N2O',      '3.A'),
            ('ABW', 'N2O',     'M.AG'),
            ('ABW', 'N2O', 'M.AG.ELV'),
            ('ANT', 'CH4',      '3.A'),
            ('ANT', 'CH4',     'M.AG'),
            ('ANT', 'N2O',      '3.A'),
            ('ANT', 'N2O',     'M.AG'),
            ('ANT', 'N2O', 'M.AG.ELV'),
            ('NIU', 'CH4', 'M.AG.ELV'),
            ('NIU', 'N2O',        '5'),
            ('NRU', 'CO2',      '2.D'),
            ('NRU', 'N2O',        '2'),
            ('NRU', 'N2O',      '2.G'),
            ('SHN', 'CH4',      '3.A'),
            ('SHN', 'CH4',     'M.AG'),
            ('SHN', 'N2O',      '3.A'),
            ('SHN', 'N2O',     'M.AG'),
            ('SHN', 'N2O', 'M.AG.ELV'),
            ('TKL', 'CH4', 'M.AG.ELV'),
            ('TUV', 'CO2',      '2.D'),
            ('TUV', 'N2O',        '2'),
            ('TUV', 'N2O',      '2.G'),
            ('VGB', 'CH4',      '3.A'),
            ('VGB', 'CH4',     'M.AG'),
            ('VGB', 'N2O',      '3.A'),
            ('VGB', 'N2O',     'M.AG'),
            ('VGB', 'N2O', 'M.AG.ELV')],
           names=['area', 'entity', 'category'])
```

Most prominently Agricultural methane and nitrous oxides from ABW, ANT, SRN and VGB, but others are affected as well.

They do not appear in the csv files and return as nan in the netcdf versions. The changes document between the two versions seems to report them as no change (for two examples i checked manually).

**Comment by JGuetschow** [comment]
These time series used EDGAR v6.0 data in PRIMAP-hist v2.4. EDGAR v 7.0 does not contain timeseries for these countries and sectors and neither does any other source. Thus they were dropped due to a lack of input data. Sorry this didn't make it to the data description document. I had the information in a draft document and thought it was included in the final document as well.

**Comment by coroa** [comment]
Ok, just a documentation issue then. Sad, thanks.
