### ISSUE TITLE
Potential error in third party CO2 emissions in Georgia

### ISSUE THREAD

**Issue by Discostu36** [JGuetschow/PRIMAP-hist#75]
There seems to be an artefact in the third-party data for CO2 emissions from the energy sector in Georgia
![grafik](https://github.com/JGuetschow/PRIMAP-hist/assets/30999326/1f28b49e-4a3c-4b5f-ac94-ad79dcd9386b)

https://primap.org/primap-hist/#scenario=histtp&id=geo&entity=co2

**Comment by JGuetschow** [comment]
That does not look good indeed. This part of the time-series is directly taken from CDIAC data. The decline part of the spike is Georgia's post USSR collapse emissions decline as modeled by CDIAC. For years up to 1991 CDIAC only resolves the USSR and not the current states. To downscale the USSR data to current states, currently a 5 year average is used to calculate the shares for the individual countries. As Georgia has an especially steep emissions decline this leads to pre-1992 emissions which are lower than the high 1992 value. 
I have to reconsider using the averaging period for the next PRIMAP-hist update. It is usually used for downscaling and harmonization of timeseries to avoid large impacts of single year fluctuations, but in this case it might create more problems than it solves.

**Comment by JGuetschow** [comment]
Fixed the code for v2.5.1 (to be released in March 2024)
