### ISSUE TITLE
Provenance column

### ISSUE THREAD

**Issue by rgieseke** [JGuetschow/PRIMAP-hist#78]
Version 2.5 added a `provenance` column.

The description states
```
"provenance"

Provenance of the data. Here: "derived" as it is a composite source.
```

The values in `Guetschow_et_al_2023b-PRIMAP-hist_v2.5_final_15-Oct-2023.csv` seem to always be `measured`

Should it always be `derived`? `measured` for values coming from another dataset without changes?

**Comment by JGuetschow** [comment]
Yes, derived makes more sense. That's an error

**Comment by JGuetschow** [comment]
Fixed in the code. In the next release it will be correct.
